### ISSUE TITLE
Weird link on OMP_Extractor.md

### ISSUE THREAD

**Issue by JShim-CS** [LLNL/AutoParBench#10]
Hi,
I am not sure whether support for this repository is being continued, but I just wanted to notify the developers that the Free Compiler Camp Classroom link (freecompilercamp.org/openmp-extractor/) in the OMP_Extractor.md leads to a weird gambling website (not sure if this is only happening to me).

**Comment by chunhualiao** [comment]
The funding for the project ended. The domain name was taken by other bad
actor.

**Comment by JShim-CS** [comment]
Ok thanks for letting me know.
