### ISSUE TITLE
Survey Question on the For loop in source file https:/github.com/LLNL/AutoParBench/blob/master/benchmarks/Cetus/dataracebench/DRB099-targetparallelfor2-orig-no.c line 120

### ISSUE THREAD

**Issue by quazirafi** [LLNL/AutoParBench#5]
Hello Sir/ Madam
We are from a research group at Iowa State University, USA. We want to do a survey on Github developers on the methods they used for paralleling their code. To do the survey, We want to ask three questions about this for loop:

Can you briefly explain the purpose of using pragma for this case? If the pragma contained reduction and private clauses, can you briefly mention the purposes of variables in those clauses?

How much confidence do you have about the correctness of this implementation? You can choose from 1-5 with 1 as the lowest confidence score and 5 as the highest confidence score.

(Optional) Do you actually run (interpret the code with compilation and pass input/get output) the code and see the optimization of parallelization? Yes/No

If yes, can you provide the information of what are the input and expected output of this program (the input that caused the program to run through this for-loop).
The for loop is from line 120 of file 
https:/github.com/LLNL/AutoParBench/blob/master/benchmarks/Cetus/dataracebench/DRB099-targetparallelfor2-orig-no.c
Here is a part of the code:

#pragma omp parallel for private(i)
	for (i=0; i<len; i ++ )
	{
		a[i]=(((double)i)/2.0);
		b[i]=0.0;
	}

**Comment by gleisonsdm** [comment]
Hello,

1. Can you briefly explain the purpose of using pragma for this case? If the pragma contained reduction and private clauses, can you briefly mention the purposes of variables in those clauses?

This loop was parallelized by Cetus compiler without any profitability consideration, i.e. the code was not written by a human.

2. How much confidence do you have about the correctness of this implementation? You can choose from 1-5 with 1 as the lowest confidence score and 5 as the highest confidence score.

5, as it does not have race conditions. 

Regards

**Comment by quazirafi** [comment]
Thank you so much for the reply! I am closing the issue.
